
[Java]

	[Java.Version]

		[Java.Version.Requirement]
			#
			#Whether or not to require a certain version of Java to be able to launch the modpack.
			#If someone tries to launch the modpack with a version of Java older than that specified in requiredMinJavaVersion, they'll get a message telling them how to upgrade and that the modpack will close until they relaunch it with more modern Java.
			#Note: This is *separate* from enableMinJavaVerWarning - you can have a separate version requirement and warning.
			enableMinJavaVerRequirement = true
			#
			#The minimum version of Java needed to be able to launch the modpack.
			#Note: itlt handles Java version naming scheme differences for you, meaning you can put "7" here and itlt will correctly check against "Java 1.7" internally, while values such as "15" will check against "Java 15" internally.
			requiredMinJavaVerion = 8

		[Java.Version.Warning]
			#
			#Whether or not to warn when someone tries to launch the modpack with a version of Java older than that specified in warnMinJavaVersion.
			#If this is enabled and someone does that, they'll get a message telling them how to upgrade with the option to ask later and continue launching the modpack.
			#Note: This is *separate* from enableMinJavaVerRequirement - you can have a separate version requirement and warning.
			enableMinJavaVerWarning = true
			#
			#The minimum recommended version of Java needed to skip the warning message when launching the modpack.
			warnMinJavaVersion = 8
			#
			#Some launchers (such as Twitch/CurseForge launcher) do not allow the Java version to be changed beyond Java 8.
			#Enable this option to ignore the MinJavaVerWarning on launchers where the users are unable to change the version of Java used to launch the game.
			ignoreMinJavaVerWarningWhenVerForced = true

		[Java.Version.Guide]
			#
			#The URL of the guide you want users to visit when they want 64bit Java.
			#Note: enableCustomJavaUpgradeGuide must be enabled for this to take effect.
			#Note: The URL must start with "https://" for security reasons.
			customJavaUpgradeGuideURL = "https://ozli.ga"
			#
			#Enable this if you want to be able to change the link your users are sent to when they ask for instructions on how to upgrade Java.
			#This is mainly useful for when you're using an unsupported version of this mod and the default guide is outdated.
			enableCustomJavaUpgradeGuide = false

	[Java.Memory]

		[Java.Memory.Guide]
			customMemoryAllocGuideURL = "https://ozli.ga"
			enableCustomMemoryGuide = false

		[Java.Memory.Min]

			[Java.Memory.Min.Requirement]
				#
				#Enable this to require that at least X amount of RAM is available to the modpack for allocating.
				#This is useful if you have users complaining about "OutOfMemory" crashes.
				#Note: This is *separate* from enableMinMemoryWarning - you can have a separate min RAM allocation requirement and warning.
				enableMinMemoryRequirement = true
				#
				#The minimum amount of allocated RAM in GB needed to be able to launch the modpack.
				reqMinMemoryAmountInGB = 0.5

			[Java.Memory.Min.Warning]
				#
				#Enable this to show a warning when less than X amount of RAM is available to the modpack for allocating.
				#Think of this like a recommended amount while the requirement is a minimum amount.
				#Warning: Setting this too high could make it impossible for some of your users to allocate the amount you're recommending and may actually hurt performance (see the max memory section for details).
				#Note: This is *separate* from enableMinMemoryRequirement - you can have a separate min RAM allocation requirement and warning.
				enableMinMemoryWarning = true
				#
				#The minimum recommended amount of allocated RAM in GB needed to skip the warning message when launching the modpack.
				warnMinMemoryAmountInGB = 1.0

		[Java.Memory.Max]

			[Java.Memory.Max.Requirement]
				reqMaxMemoryAmountInGB = 16.0
				#
				#Enable this to require that no more than X amount of RAM is available to the modpack for allocating.
				#This is useful for preventing users from allocating excessive amounts of RAM to the point of causing nasty GC-related lag spikes as a result.
				enableMaxMemoryRequirement = true

			[Java.Memory.Max.Warning]
				enableMaxMemoryWarning = true
				warnMaxMemoryAmountInGB = 14.0

	[Java.Arch]

		[Java.Arch.Requirement]
			#
			#Whether or not to require 64bit Java to be able to launch the modpack.
			#If this is enabled and someone tries to launch the modpack with 32bit Java, they'll get a message telling them how to upgrade and the modpack will close until they relaunch it with 64bit Java.
			#Note: Enabling this overrides enable64bitWarning.
			enable64bitRequirement = true

		[Java.Arch.Warning]
			#
			#Whether or not to warn when someone tries to launch the modpack with 32bit Java.
			#If this is enabled and someone does that, they'll get a message telling them how to upgrade with the option to ask later and continue launching the modpack.
			enable64bitWarning = true

		[Java.Arch.Guide]
			#
			#The URL of the guide you want users to visit when they want 64bit Java.
			#Note: enableCustom64bitJavaGuide must be enabled for this to take effect.
			#Note: The URL must start with "https://" for security reasons.
			custom64bitJavaGuideURL = "https://ozli.ga"
			#
			#Enable this if you want to be able to change the link your users are sent to when they ask for instructions on how to get 64bit Java.
			#This is mainly useful for when you're using an unsupported version of this mod and the default guide is outdated.
			enableCustom64bitJavaGuide = false

[Anticheat]
	#
	#Whether or not to detect and report known cheats to servers with itlt installed and anti-cheat enabled.
	#Note: Disabling this won't suddenly allow you to cheat on said servers - it'll simply prevent you from joining them at all.
	#Note: Depending on the server, you may be able to join it with cheats installed even if anti-cheat is enabled on the server. The action the server takes towards cheaters is down to the server's staff.
	enableAnticheat = true
	#
	#Enable this if you want itlt to automatically delete known cheat mods so that they don't run on next launch.
	#This feature is intended to prevent accidental cheating on servers. You'll probably want to disable this setting if you want to cheat on singleplayer.
	#Note: enableAnticheat must be enabled for this to take effect.
	enableAutoRemovalOfCheats = true

[ServerList]
	enableCustomServerListEntries = false

[Display]

	[Display.WindowTitle]
		#
		#Whether or not to automatically use your modpack's display name instead of the customWindowTitleText when launching from the Technic Launcher.
		#Note: This will override the contents of customWindowTitleText when launching from a Technic Platform modpack.
		#Note: enableCustomWindowTitle must be enabled for this to take effect.
		enableUsingTechnicDisplayName = true
		#
		#The name you want your Minecraft window to be.
		#Note: enableCustomWindowTitle must be enabled for this to take effect.
		customWindowTitleText = ""
		#
		#Enable this if you want the game's version to be appended to the end of your customWindowTitleText.
		#For example: "ModpackName (Minecraft* 1.16.3)")
		#Note: This is enabled by default because Mojang went out of their way to prevent modders from changing the window title easily - this setting is a happy middle ground where both modpack authors' and Mojang's preferences are respected.
		enableAppendingToCustomTitle = true
		#
		#Enable this if you want to change the name of the Minecraft window.
		enableCustomWindowTitle = true

	[Display.Icon]
		#
		#Enable this if you want itlt to automatically use your modpack's icon instead of the icon.png when launching from the Technic Launcher.
		#Note: This will override the icon.png when launching from a Technic Platform modpack.
		#Note: enableCustomIcon must be enabled for this to take effect.
		enableUsingTechnicIcon = true
		#
		#Enable this if you want to change the window icon of the Minecraft window.
		#Note: The icon needs to be placed in config\itlt\icon.png and be no larger than 128px squared.
		#Warning: Icon sizes beyond 128px squared can cause blurriness or even crashes on certain operating systems!
		enableCustomIcon = false

