
#Client
[client]
	#Set this to true if all items should be transferred when autofilling an inventory, as opposed to only transferring items that are already in that inventory.
	allItems = true
	#Set this to true if the hotbar should not be messed with when filling.
	hotbarLocked = true
	#Set this to true if the hotbar lock GUI button should be visible. False if it shouldn't be visible.
	hotbarButtonEnabled = true

