
#Enable or Disable Enchantments
[Telekinesis]
	Enable = true

[Aiming]
	Enable = true

[Smelting-Touch]
	Enable = true

[Ender-Slayer]
	Enable = true

[Experience]
	Enable = true

[Fireworks]
	Enable = true

[Growth]
	Enable = true

[Harvesting]
	Enable = true

[Leaf-Shatter]
	Enable = true

[Life-Steal]
	Enable = true

[Magma-Walker]
	Enable = true

[Might]
	Enable = true

[Rainbow]
	Enable = true

[Replenish]
	Enable = true

[Speed]
	Enable = true

[Ore-Shatter]
	Enable = true

[Wood-Shatter]
	Enable = true

[Destroyer]
	Enable = true

[Sniper]
	Enable = true

[Tracker]
	Enable = true

