
#Screen Config
[screen]
	#The duration of screen background and blur radius animation in milliseconds. (0 = OFF)
	#Range: 0 ~ 800
	animationDuration = 800
	#The blur effect radius, higher values result in a small loss of performance.
	#Range: 2 ~ 18
	blurRadius = 10
	#Screen black background opacity in game, higher values will get darker.
	#Range: 0.0 ~ 0.8
	backgroundAlpha = 0.4
	#A list of GUI screen superclasses that won't activate blur effect when opened.
	blurExclusions = []
	#Add blur effect to world renderer when opened, it is incompatible with OptiFine's FXAA shader or some mods.
	blurEffect = true

#Font Engine Config
[font]
	#Enable font anti-aliasing.
	antiAliasing = true
	#Enable high precision rendering, this is very useful especially when the font is very small.
	highPrecision = true
	#The resolution level of font, higher levels would better work with high resolution monitors.
	#Reference: 1 (Standard, 1.5K Fullscreen), 2 (High, 2K~3K Fullscreen), 3 (Ultra, 4K Fullscreen)
	#Range: 1 ~ 3
	resolutionLevel = 3
	#Replace the default font renderer of vanilla to that of Modern UI.
	globalRenderer = true
	#The default font size for texts with no size specified.
	#Range: 12 ~ 20
	defaultFontSize = 16
	#The mipmap level for font textures.
	#Range: 0 ~ 4
	mipmapLevel = 4
	#Allow global font renderer to draw text with shadow, setting to false can improve performance.
	allowShadow = true
	#The font name with the highest priority to use, the built-in font is always the second choice.
	preferredName = ""
	#Enable mipmap for font textures, this makes font will not be blurred when scaling down.
	enableMipmap = true

